---
# This playbook deploys all sub playbooks

- name: apply common configuration to all nodes
  hosts: search_head  
  vars:
    # splunk binary to install
    splunk_binary: 'splunk-7.1.0-2e75b3406c5b-Linux-x86_64.tgz'

  roles:    
    - search_head


